# Note that the example .travis.yml file for child projects lives in /install.
sudo: required
language: php
dist: trusty

php:
  - 5.6

matrix:
  fast_finish: true

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"
  # Cache front end dependecies to dramatically improve build time.
  # - "docroot/themes/custom/mytheme/node_modules"
  # - "docroot/themes/custom/mytheme/bower_components"

addons:
  ssh_known_hosts:
  # - svn-4786.devcloud.hosting.acquia.com
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  # code climate integration
  code_climate:
    secure: hhFEmNdJQU4ui8ph2cdATzjU3QVxLdrugJSTcgoKJ0QVi7sV1Bk0LHa47icb6iCGg7mbljYoyeeVRZlCjVzx35vC+s34049WJDo/WMlZuscB3a6Z4UwDXC0oJl4j2VzCgdXPo9S40aDrtiLyM6Gj4ETy/kf4idL5PYVvEQiERsN7H9bchjoLtmNIbTYYyNVFqRoRwSvc0g2RT+Fu43hFeTQiHpNJ9bUZyautQKJ/gga2wirCiIqBrZPbocRkdJSxwJEzfQwKTu4AYjMtoRMW7W+mZsiXmxdteM8CpEM5PbXREC2AzXS9F8/+IGDk5riqVGobvvFtnp26MJBBS8UuVRHvN05D7Hf3FH5URg7EwRw/EWSSiGp/gmknRN2WGBiO/AQzekJ2oXHLTWbYxOYxfzjWFFD9gPbLNb3IdZhwYQnHjqkKjeYv88umo0mE1AUI4VAQKmQKfMQW/t3TN2fP2JWu4sghG1G1AJP015jAJ0h0S+esG+2k9UJMGgtdvE/xyjVaXm8tj+w71PiICo+1NNIg/R6NsD5imhJ0KZRydg5zAm2hLZQl5etmuaXajl9otgBqbX5xs2ueNcudecXn2CIfxCOyky175aDHcFZCYa8TkQxD7i8BQrERma1BFVUGv7Z+NDhFagtVcjCssn7jk9/7C2CCjQ0y6zBjer5MZtE=
  # saucelabs integration
  #sauce_connect:
  #  username: ttoman
  #  secure: fGSseUWaHKvCvWG/uxt7PMq17w39fwc7dtRM8X20KGVmqDeIk2vfE3ulIvTVE8vhjIDaywkq0jBAwPMwHQu/DUzoW6oAhZHp6t7lEdluLKQ2sBv2276vTKzgJR5kcynPNzjfuttzC97PWysL2+JqgBK1l5V2Nj7d6vLRCv2JVxhUHJCgDRkxZSXiUw5bTaGagIa5HHJYRmMvYIRoTgrL/KpYfWMH/dNuCKnsuB0CG2gORzigCzlWfutuHjErKJGWbnNoxL3lhxHjXRVUOxqQ8fwyZwgUsipkA7s8HtqFPJCOTrcNqcujGfCX1ycRWQym1X/DYkW9uXrQi2VHJT+QFG5Kuj1sLS9y2M4fnyWaSueRgTNchNssCCBFFBotiPQXFvRYwJfrZlCvRSk/LbSwl84TaJ1bqvoxIp+QkbsUf+aumyIgu0EmENYuDnCIxbzYegY+oWh5RwdZ9VAoVmaWpJOSzYdGMs78OIEBSdFr3wr37LGg4PuIDdAeJGAlLDFb5nc/Gfaqn+eMsKkpFTX1Uja0lKB3+osAnrZUf3pBZVkDlAQmdYu/wG++8ttNbSDSq9JUMtVYhqYcK94X+X+DucUnWKTIm7Jwl1qjCTbJpuPLl/zJe8mhXj3yC95LbvyEkv8PZDZeVDIRrpA64DCIEyEDi/gXMPZlKhC/OZgyqpI=

# @see https://docs.travis-ci.com/user/notifications
notifications:
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'
  slack:
    secure: dzFsX8by42nys1YDMsX7XpANi/F42Wonj9oSf5frexWY4CX/SryQNZRtysRbLeEqymVSEWdFfyfG6O+Nu7CjuyKoQvuxI5oU+8N7qmvpkT8BFG7pjb+trOS7ykJZQ9d/U7ltSoPfgK9nZOD7h33jk1Ub0YL1fSngUqJe1GjFTk4atsEB56XGO/dHj634OJ7TVXPwwjDUAsKC/ZAeoH6VtfZUWyY/XJDH008Xq1GEx54QlcNKiPhbWYNCbYPrphnKs4RX6ypkzKqIXdeZPm2qkyOO/pu6pRJrb9cfX739BgKmyksmTH3jhddGjuwFQHQ1Ur9/VGtGVCBHPl3BenMNf65/Vjt26d0NoD1duQ7z2XUfcwp50CCC24WTR9nHuC06+1AxyyUNBpcvhx+WeJ4z7TwLIl3ZBKcLtTRGq43gNHP8RUTH2RxFZlcbN13NomT7gjC63ugyOAoTgECV+CCLMOblH11Gx+Ufqj5pHn1vqh4gO2IAKF4rFmP7tQ+iKFPZT/jPwj4ZHr2036yy75k5YqyU+2CYSdxIULE9kNhfmoz7omzPlW4+AprWTjMgN0v9A9skXSr9FZ01wX8mBxSxpM1g7Q8RfPkU8MmNzn2Fb1bp1BvAvqiIwsaWAplka/8MHuY1L8vqJtKIIeybw11wwpFgx7b9IbFwRnO+VK77Fjw=


before_install:
  # Enable aliases for non-interactive shell.
  - shopt -s expand_aliases
  - composer selfupdate
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Enable $_ENV variables in PHP.
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - mysql -u root -e 'CREATE DATABASE drupal;'

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - composer install
  - export PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH
  # Install proper version of node for front end tasks.
  - nvm install 4.4.1
  - nvm use 4.4.1
  # Initialize drupal console default configuration.
  - drupal init
  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  - sudo apt-get install xvfb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Installs chromedriver to vendor/bin.
  - ./vendor/acquia/blt/scripts/linux/install-chrome.sh $TRAVIS_BUILD_DIR/vendor/bin

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
  # Verify that no git diffs (caused by line ending variation) exist.
  # - git diff --exit-code
  # The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to run the site on Travis CI.
  - drupal yaml:update:value project.yml project.local.hostname '127.0.0.1:8888'


script:
  - blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate:test

# Support for CodeClimate
after_script:
  - ./vendor/bin/test-reporter

deploy:
   - provider: script
     script: blt deploy -Ddeploy.commitMsg="Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" -Ddeploy.branch="${TRAVIS_BRANCH}-build"
     skip_cleanup: true
     on:
       branch: master
       php: 5.6
