# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php
dist: trusty

php:
  - 5.6

matrix:
  fast_finish: true

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"
  # Cache front end dependecies to dramatically improve build time.
  - "docroot/themes/custom/patternlab/node_modules"
  - "docroot/themes/custom/patternlab/bower_components"

addons:
  ssh_known_hosts:
  # - svn-4786.devcloud.hosting.acquia.com
    - svn-5223.devcloud.hosting.acquia.com
    - svn-6182.devcloud.hosting.acquia.com

  apt:
    sources:
    - xvfb

  # code climate integration
  code_climate:
    secure: hhFEmNdJQU4ui8ph2cdATzjU3QVxLdrugJSTcgoKJ0QVi7sV1Bk0LHa47icb6iCGg7mbljYoyeeVRZlCjVzx35vC+s34049WJDo/WMlZuscB3a6Z4UwDXC0oJl4j2VzCgdXPo9S40aDrtiLyM6Gj4ETy/kf4idL5PYVvEQiERsN7H9bchjoLtmNIbTYYyNVFqRoRwSvc0g2RT+Fu43hFeTQiHpNJ9bUZyautQKJ/gga2wirCiIqBrZPbocRkdJSxwJEzfQwKTu4AYjMtoRMW7W+mZsiXmxdteM8CpEM5PbXREC2AzXS9F8/+IGDk5riqVGobvvFtnp26MJBBS8UuVRHvN05D7Hf3FH5URg7EwRw/EWSSiGp/gmknRN2WGBiO/AQzekJ2oXHLTWbYxOYxfzjWFFD9gPbLNb3IdZhwYQnHjqkKjeYv88umo0mE1AUI4VAQKmQKfMQW/t3TN2fP2JWu4sghG1G1AJP015jAJ0h0S+esG+2k9UJMGgtdvE/xyjVaXm8tj+w71PiICo+1NNIg/R6NsD5imhJ0KZRydg5zAm2hLZQl5etmuaXajl9otgBqbX5xs2ueNcudecXn2CIfxCOyky175aDHcFZCYa8TkQxD7i8BQrERma1BFVUGv7Z+NDhFagtVcjCssn7jk9/7C2CCjQ0y6zBjer5MZtE=
  # saucelabs integration
#  sauce_connect:
#    username: ttoman
#  jwt:
#    secure: IEI6dd8+Xj3yxfJWvPLwyXra7eqkxR7UoHp5ofMxG+djWCKnwHR6H12rgkTZ5nbrv1DeX+DBOMI/ZraLWO89EzW+LLEiJbqpJNF5dulUE+MIpC11JiEiE+87g0VQfqu4l33tFHdrTwpBuHSCCVcAWMv7byPlaM34q2d8UhpP8SgJxhdzrK9UlpN66zi5tti+i59b4iRnnn1V1ATS2GIW2LRWt9OoJDgGOpQKtrnl3jdcw51v6rMnCvFEI7lLxKR2JJ0xC7IRxwvSvM+9Ku8njw0G0owKz4obNKf62sMGsV1d93SMcHDNaok5lf3eOBKg2Q21JPUw7vab+Kej32ZyCtqQKAVWoZaL/4LVsaeHPdZDbjFudTi98GdA8yIlyOfsqIVXNgYGsPL+FObRFxPezMM3laVQuvZCTI+x+rhctxwBlRF8CwbyaDzJ/wTgk6HW0eQwhCQzEpriNeJyez7VrXOeA6rfUdaxbs3f/NiZEszAL6UBkteJ0VVDbGmoyyPtm4vw2aM6ujLrIe/BAkku1wstzVYy1aTUEY6IxdgMkxEOyU42z2UmBOUIEeIg4cCE6qIgckpLtrW0YCYUmhX9eDeLl9dIO8W617hhil3G9nNvLmnaDl/puUprM6mIUN8HGzrHmBbTqYxY/sAizgKXYQI+P5z401ZQ++a2WTilpFI=

# @see https://docs.travis-ci.com/user/notifications
notifications:
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'
  slack:
    secure: dzFsX8by42nys1YDMsX7XpANi/F42Wonj9oSf5frexWY4CX/SryQNZRtysRbLeEqymVSEWdFfyfG6O+Nu7CjuyKoQvuxI5oU+8N7qmvpkT8BFG7pjb+trOS7ykJZQ9d/U7ltSoPfgK9nZOD7h33jk1Ub0YL1fSngUqJe1GjFTk4atsEB56XGO/dHj634OJ7TVXPwwjDUAsKC/ZAeoH6VtfZUWyY/XJDH008Xq1GEx54QlcNKiPhbWYNCbYPrphnKs4RX6ypkzKqIXdeZPm2qkyOO/pu6pRJrb9cfX739BgKmyksmTH3jhddGjuwFQHQ1Ur9/VGtGVCBHPl3BenMNf65/Vjt26d0NoD1duQ7z2XUfcwp50CCC24WTR9nHuC06+1AxyyUNBpcvhx+WeJ4z7TwLIl3ZBKcLtTRGq43gNHP8RUTH2RxFZlcbN13NomT7gjC63ugyOAoTgECV+CCLMOblH11Gx+Ufqj5pHn1vqh4gO2IAKF4rFmP7tQ+iKFPZT/jPwj4ZHr2036yy75k5YqyU+2CYSdxIULE9kNhfmoz7omzPlW4+AprWTjMgN0v9A9skXSr9FZ01wX8mBxSxpM1g7Q8RfPkU8MmNzn2Fb1bp1BvAvqiIwsaWAplka/8MHuY1L8vqJtKIIeybw11wwpFgx7b9IbFwRnO+VK77Fjw=


before_install:
  # Decrypt private SSH key id_rsa_blt.enc, save as ~/.ssh/id_rsa_blt.
  #- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -K $encrypted_3fec15fb840c_key -iv $encrypted_3fec15fb840c_iv -in travis_acquia_pri.ppk.enc -out ~/.ssh/id_rsa -d; chmod 600 ~/.ssh/id_rsa; ls -lash ~/.ssh; eval "$(ssh-agent -s)"; ssh-add ~/.ssh/id_rsa; fi

  # Enable aliases for non-interactive shell.
  - shopt -s expand_aliases
  - composer selfupdate
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Enable $_ENV variables in PHP.
  - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Ensure that always_populate_raw_post_data PHP setting: Not set to -1 does not happen.
  - echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
  # Repo for newer Node.js versions
  #- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  #- sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  #- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  #- sudo apt-get update -qq
  #- sudo apt-get install -y -qq yarn


install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - composer install
  - export PATH=$TRAVIS_BUILD_DIR/vendor/bin:$PATH
  # Install proper version of node for front end tasks.
  - nvm install 4.4.1
  - nvm use 4.4.1
  # Initialize xvfb (see https://docs.travis-ci.com/user/gui-and-headless-browsers)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Installs chromedriver to vendor/bin.
  - ./vendor/acquia/blt/scripts/linux/install-chrome.sh $TRAVIS_BUILD_DIR/vendor/bin
  # Use JDK 8.
  - jdk_switcher use oraclejdk8

before_script:
  # Clear drush release history cache, to pick up new releases.
  - rm -f ~/.drush/cache/download/*---updates.drupal.org-release-history-*
  # Verify that no git diffs (caused by line ending variation) exist.
  # - git diff --exit-code
  # The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to run the site on Travis CI.
  - yaml-cli update:value blt/project.yml project.local.hostname '127.0.0.1:8888'


script:
  - travis_wait blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate:test -Dblt.verbose=true

# Support for CodeClimate
after_script:
  - ./vendor/bin/test-reporter

before_deploy:
# Decrypt private key
  - openssl aes-256-cbc -K $encrypted_3fec15fb840c_key -iv $encrypted_3fec15fb840c_iv -in travis_acquia_pri.ppk.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - ls -lash ~/.ssh
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa

deploy:
   - provider: script
     script: blt deploy -Ddeploy.commitMsg="Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" -Ddeploy.branch="${TRAVIS_BRANCH}-build"
     skip_cleanup: true
     on:
       branch: master
       php: 5.6
