# Note that the example .travis.yml file for child projects lives in /install.
# Temporarily use legacy infrastructure until Travis resolves MySQL issues with their containerized infrastructure.
# @see https://github.com/travis-ci/travis-ci/issues/6842
sudo: required
language: php
dist: trusty

php:
  - 5.6

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"
  # Cache front end dependecies to dramatically improve build time.
  - "docroot/themes/custom/mytheme/node_modules"
  - "docroot/themes/custom/mytheme/bower_components"

addons:
  ssh_known_hosts:
  # - svn-4786.devcloud.hosting.acquia.com
  - svn-5223.devcloud.hosting.acquia.com
  - svn-6182.devcloud.hosting.acquia.com

# @see https://docs.travis-ci.com/user/notifications
notifications:
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'
  slack:
    secure: dzFsX8by42nys1YDMsX7XpANi/F42Wonj9oSf5frexWY4CX/SryQNZRtysRbLeEqymVSEWdFfyfG6O+Nu7CjuyKoQvuxI5oU+8N7qmvpkT8BFG7pjb+trOS7ykJZQ9d/U7ltSoPfgK9nZOD7h33jk1Ub0YL1fSngUqJe1GjFTk4atsEB56XGO/dHj634OJ7TVXPwwjDUAsKC/ZAeoH6VtfZUWyY/XJDH008Xq1GEx54QlcNKiPhbWYNCbYPrphnKs4RX6ypkzKqIXdeZPm2qkyOO/pu6pRJrb9cfX739BgKmyksmTH3jhddGjuwFQHQ1Ur9/VGtGVCBHPl3BenMNf65/Vjt26d0NoD1duQ7z2XUfcwp50CCC24WTR9nHuC06+1AxyyUNBpcvhx+WeJ4z7TwLIl3ZBKcLtTRGq43gNHP8RUTH2RxFZlcbN13NomT7gjC63ugyOAoTgECV+CCLMOblH11Gx+Ufqj5pHn1vqh4gO2IAKF4rFmP7tQ+iKFPZT/jPwj4ZHr2036yy75k5YqyU+2CYSdxIULE9kNhfmoz7omzPlW4+AprWTjMgN0v9A9skXSr9FZ01wX8mBxSxpM1g7Q8RfPkU8MmNzn2Fb1bp1BvAvqiIwsaWAplka/8MHuY1L8vqJtKIIeybw11wwpFgx7b9IbFwRnO+VK77Fjw=

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install

install:
  - nvm install 4.4.1
  - nvm use 4.4.1
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - echo "sendmail_path=sendmail -t -i" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - source $BLT_DIR/scripts/travis/setup_project

script:
  - source $BLT_DIR/scripts/travis/run_tests

before_deploy:
# Decrypt private key
  - openssl aes-256-cbc -K $encrypted_3fec15fb840c_key -iv $encrypted_3fec15fb840c_iv -in travis_acquia_pri.ppk.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - ls -lash ~/.ssh
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa

deploy:
   - provider: script
     script: "$BLT_DIR/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: master
       php: 5.6
