site_name: DV Documentation
site_description: 'DV - Transparency Project'
site_url: "http://dev.trans.ink"
# Repository
repo_name: 'GitHub'
repo_url: https://github.com/dreamfony/dv
edit_uri: 'docroot/profiles/dv/docs'

docs_dir: 'docroot/profiles/dv/docs/'
strict: true

theme: readthedocs

#use_directory_urls

extra_javascript:
  - js/fix_search.js
extra_css:
  - css/dv_theme.css

#google_analytics: ['']
markdown_extensions:
  - toc:
      permalink: True

# Page tree
pages:
  - Home: 'index.md'
  - 'Overview': 'README.md'
  - Features:
  - Operations:
      - Deployment:
  - Architecture:
    - 'System Overview': 'architecture.md'
    - Content:
      - 'Content': 'architecture/content.md'
      - 'Answer': 'architecture/answer_comment.md'
      - 'Activity': 'architecture/activity_comment.md'
      - 'Default Comment': 'architecture/default_comment.md'
      - 'Log': 'architecture/log_comment.md'
    - Organisations:
      - 'Organisations': 'architecture/organisations.md'
      - 'Positions': 'architecture/positions.md'
    - Mailing List:
      - 'Mailing List': 'architecture/mailing_list.md'
      - 'Mailing List Activity': 'architecture/mailing_list_activity.md'
      - 'Mailing List Recipients': 'architecture/mailing_list_recipients.md'
    - 'Sending Emails': 'architecture/sending_emails.md'
    - 'Receiving Emails': 'architecture/recieving_emails.md'
    - 'Moderation': 'architecture/moderation_activity.md'
  - Testing:
  - Documentation Architecture:
  - Feature Documentation:
  - Overview of issue labels:
  - Designer Documentation: