site_name: DV Documentation
site_description: 'DV - Transparency Project'
site_url: "http://dev.trans.ink"
# Repository
repo_name: 'GitHub'
repo_url: https://github.com/dreamfony/dv
edit_uri: 'docroot/profiles/dv/docs'

docs_dir: 'docroot/profiles/dv/docs/'
strict: true

theme: readthedocs

#use_directory_urls

extra:
  logo: images/unicorn.png
extra_javascript:
  - js/fix_search.js
extra_css:
  - css/theme.css

#google_analytics: ['']
markdown_extensions:
  - toc:
      permalink: True

# Page tree
pages:
  - 'Home': 'index.md'
  - 'Architecture': 'architecture.md'