site_name: DV Documentation
site_description: 'DV - Transparency Project'
site_url: "http://dev.trans.ink"
# Repository
repo_name: 'GitHub'
repo_url: https://github.com/dreamfony/dv

#theme_dir: '_theme/material'
theme: readthedocs
strict: true

docs_dir: 'docroot/profiles/dv/docs'
#extra:
  #logo: images/limitless-logo.png

#google_analytics: ['UA-26768009-4', 'docs.projectlimitless.io']
#extra_javascript:
#  - readme/js/fix_search.js
#extra_css: [themefix.css]
markdown_extensions:
  - toc:
      permalink: True

# Page tree
pages:
  - Home: 'index.md'
  - Overview: 'architecture.md'
  - Architecture:
      - Content: architecture/content.md