project:
    machine_name: dv
    prefix: DV
    human_name: Dv
    profile:
        name: dv
    local:
        protocol: http
        hostname: 'local.${project.machine_name}.com'
git:
    default_branch: master
    remotes:
        - 'dv1@svn-6182.devcloud.hosting.acquia.com:dv1.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend-setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend-build configured.'''
    post-deploy-build:
        dir: '${docroot}'
        command: 'echo ''No post-deploy build configured.'''
    post-setup-build:
        dir: '${docroot}'
        command: 'echo ''No post-setup build configured.'''
import: '${repo.root}/custom/custom.xml'
modules:
    ci:
        enable: {  }
        uninstall: [acquia_connector, shield]
    deploy:
        enable: [acquia_connector, shield, geo_area_group, geo_area_migrate, import_organisations, organisation_group, dv_user_groups]
        uninstall: [devel, field_ui, views_ui]
    local:
        enable: [devel, field_ui, seckit, features_ui, views_ui, geo_area_group, geo_area_migrate, dv_issue, dv_organisation_migrate, dv_organisation_group]
        uninstall: [acsf, acquia_connector]
drupal:
  account.name: admin
  account.password: admin
  account.mail: dv@dv.com
# Skip this until we fix DV profile
disable-targets:
    setup:
        config-import: true
        git-hooks: true
    tests:
        phpunit: true
    local:
        sync: true
pimpmylog:
    enable: [syslog]
    uninstall: [dblog]

