system.dmt_configuration:
  title: 'DMT Core'
  description: 'Configure and Manage DMT'
  route_name: dmt_configuration.dmtcore
  parent: 'system.admin'
  weight: -95

dmt_configuration.dmt_organisation:
  title: 'Organisations'
  description: 'Manage Organisations'
  route_name: <none>
  parent: system.dmt_configuration
  weight: 10

dmt_configuration.dmt_survey:
  title: 'Surveys'
  description: 'Manage Surveys'
  route_name: <none>
  parent: system.dmt_configuration
  weight: 20


dmt_configuration.dmt_user:
  title: 'Users'
  description: 'Manage Users'
  route_name: <none>
  parent: system.dmt_configuration
  weight: 30

dmt_configuration.dmt_user.view:
  title: 'Manage Users'
  description: 'Manage Users'
  route_name: view.user_admin_people.page_1
  parent: dmt_configuration.dmt_user
  route_parameters: { status: '1' }
  weight: 10

dmt_configuration.dmt_activities:
  title: 'Activities'
  description: 'Manage Activities'
  route_name: <none>
  parent: system.dmt_configuration
  weight: 40

dmt_configuration.dmt_settings:
  title: 'Site settings'
  description: 'Configure Site'
  route_name: <none>
  parent: system.dmt_configuration
  weight: 50

dmt_configuration.dmt_dashboard:
  title: 'DMT Admin Dashboard'
  parent: system.dmt_configuration
  route_name: page_manager.page_view_administrator_dashboard_administrator_dashboard-panels_variant-0
  weight: 100
  options:
      attributes:
        target: _blank