workflows.workflow.*.third_party.moderation_state_machine_chain:
  type: mapping
  label: 'Moderation State Machine Transition Settings'
  mapping:
    parent_transitions:
      type: array
      label: 'Parent Transitions'
    transition_descriptions:
      type: array
      label: 'Descriptions'
