workflow.type_settings.activity_workflow:
  type: mapping
  mapping:
    states:
      type: sequence
      label: 'Additional state configuration for content moderation'
      sequence:
        type: mapping
        label: 'States'
        mapping:
          published:
            type: boolean
            label: 'Is published'
          default_revision:
            type: boolean
            label: 'Is default revision'
    entity_types:
      type: sequence
      label: 'Entity types'
      sequence:
        type: sequence
        label: 'Bundles'
        sequence:
          type: string
          label: 'Bundle ID'
