training_entity_config_auto.marko_entity_useless.*:
  type: config_entity
  label: 'Marko entity useless config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    message:
      type: text
      label: 'Text'
