vagrant_public_ip: "192.168.1.55"

vagrant_synced_folder_default_type: ""

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/dv
    type: nfs
    mount_options: ["rw","vers=3","udp","nolock"]
    create: true