services:
  dmt_domain_config.factory:
    class: Drupal\dmt_domain_config\Config\ConfigFactory
    tags:
      - { name: event_subscriber }
      - { name: service_collector, tag: 'config.factory.override', call: addOverride }
    arguments: ['@config.storage', '@event_dispatcher', '@config.typed']
    calls:
      - [setDomainNegotiator, ['@domain.negotiator']]

  config.factory:
    alias: dmt_domain_config.factory


