domain.record.*.third_party.dmt_domain_config:
  type: mapping
  label: 'DMT Domain Config'
  mapping:
    group:
      type: integer
      label: 'Group'
    template:
      type: string
      label: 'Template'
