announcement.admin:
  title: 'Check announcement'
  description: "Testing menu"
  parent: system.admin_structure
  route_name: entity.announcement.collection
  weight: 100
  menu_name: announcement_admin
  options:
    attributes:
      target: _blank
